import type { Metadata } from "next";
import { AlertIcon, ShieldIcon, UserIcon } from "@/components/icons";
import { getCurrentUser } from "@/server/auth/session";

export const metadata: Metadata = { title: "Configurações" };

export default async function SettingsPage() {
  const user = await getCurrentUser();
  return <div className="max-w-4xl"><header><p className="text-sm font-semibold text-[#145c43]">Conta</p><h1 className="mt-1 text-3xl font-extrabold tracking-[-.045em] sm:text-4xl">Configurações e privacidade</h1><p className="mt-3 leading-7 text-[#5b655e]">Revise seus dados e entenda os controles previstos para a versão integrada.</p></header>
    <section className="card mt-8 overflow-hidden"><div className="flex items-center gap-3 border-b border-[#e3e6e1] px-5 py-4 sm:px-6"><UserIcon className="text-[#145c43]" size={19} /><h2 className="font-extrabold">{user?.mode === "supabase" ? "Perfil conectado" : "Perfil demonstrativo"}</h2></div><div className="grid gap-5 p-5 sm:grid-cols-2 sm:p-6"><div><label className="field-label" htmlFor="settings-name">Nome</label><input className="field-input" defaultValue={user?.displayName || ""} disabled id="settings-name" /></div><div><label className="field-label" htmlFor="settings-email">E-mail</label><input className="field-input" defaultValue={user?.email || ""} disabled id="settings-email" /></div></div></section>
    <section className="card mt-5 overflow-hidden"><div className="flex items-center gap-3 border-b border-[#e3e6e1] px-5 py-4 sm:px-6"><ShieldIcon className="text-[#145c43]" size={19} /><h2 className="font-extrabold">Controles de dados planejados</h2></div><ul className="divide-y divide-[#e3e6e1] px-5 sm:px-6"><li className="flex items-center justify-between gap-4 py-5"><div><p className="font-bold">Retenção do PDF</p><p className="mt-1 text-sm text-[#5b655e]">Sugestão atual: 30 dias</p></div><span className="rounded-full bg-[#ecefeb] px-3 py-1 text-xs font-bold text-[#58625b]">Pendente</span></li><li className="flex items-center justify-between gap-4 py-5"><div><p className="font-bold">Uso para melhoria do produto</p><p className="mt-1 text-sm text-[#5b655e]">Exigirá consentimento separado</p></div><span className="rounded-full bg-[#dff3e8] px-3 py-1 text-xs font-bold text-[#145c43]">Desativado</span></li></ul></section>
    <section className="mt-5 rounded-[1.125rem] border border-[#e4beb9] bg-[#fff7f5] p-5 sm:p-6"><div className="flex items-start gap-3"><AlertIcon className="mt-0.5 shrink-0 text-[#9a3e34]" /><div><h2 className="font-extrabold text-[#7f3028]">Excluir conta e dados</h2><p className="mt-2 text-sm leading-6 text-[#6c5652]">A autenticação já está preparada, mas a limpeza coordenada de arquivos, jobs e conta será entregue junto da persistência do fluxo. O botão permanece indisponível para evitar exclusão incompleta.</p><button className="mt-4 rounded-full border border-[#d7aaa4] px-4 py-2 text-sm font-bold text-[#9a3e34]" disabled type="button">Excluir conta</button></div></div></section>
  </div>;
}
