import Link from "next/link";
import type { Metadata } from "next";
import { AlertIcon, ArrowRightIcon, DownloadIcon, LockIcon, ShieldIcon, UserIcon } from "@/components/icons";
import { createClient } from "@/lib/supabase/server";
import { getCurrentUser } from "@/server/auth/session";
import { deleteAccountAction, updateImprovementConsentAction } from "./actions";

export const metadata: Metadata = { title: "Configurações" };

export default async function SettingsPage() {
  const user = await getCurrentUser();
  const supabase = await createClient();
  const { data: profile } = user ? await supabase.from("profiles").select("product_improvement_consent_at").eq("id", user.id).maybeSingle() : { data: null };
  const consented = Boolean(profile?.product_improvement_consent_at);

  return <div className="max-w-4xl">
    <header><p className="eyebrow">Conta</p><h1 className="mt-4 text-4xl font-extrabold tracking-[-.055em] sm:text-5xl">Configurações</h1><p className="mt-4 max-w-xl leading-7 text-[#5b655e]">Gerencie seu perfil, seus consentimentos e seus dados no MatchCV.</p></header>
    <div className="mt-8 space-y-5">
      <section className="card overflow-hidden"><div className="flex items-center gap-3 border-b border-[#e8ebe6] px-5 py-4 sm:px-6"><span className="grid size-9 place-items-center rounded-xl bg-[#dff3e8] text-[#145c43]"><UserIcon size={18} /></span><div><h2 className="font-extrabold">Perfil conectado</h2><p className="text-xs text-[#69736c]">Dados básicos da sua conta</p></div></div><div className="grid gap-5 p-5 sm:grid-cols-2 sm:p-6"><div><p className="text-xs font-bold uppercase tracking-[.1em] text-[#89928c]">Nome</p><p className="mt-2 font-bold">{user?.displayName || "Não informado"}</p></div><div><p className="text-xs font-bold uppercase tracking-[.1em] text-[#89928c]">E-mail</p><p className="mt-2 break-all font-bold">{user?.email || "Não informado"}</p></div></div></section>
      <section className="card p-5 sm:p-6"><div className="flex items-start gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-[#dff3e8] text-[#145c43]"><ShieldIcon size={18} /></span><div><h2 className="font-extrabold">Consentimento opcional</h2><p className="mt-1 text-sm text-[#69736c]">Ajude a melhorar o produto</p></div></div><p className="mt-5 max-w-2xl text-sm leading-6 text-[#5b655e]">Permitir o uso futuro de dados para melhoria do produto é opcional. Isso não autoriza treinamento com seu currículo e pode ser revogado a qualquer momento.</p><form action={updateImprovementConsentAction} className="mt-5 flex flex-col gap-4 rounded-xl bg-[#fafbf8] p-4 sm:flex-row sm:items-center sm:justify-between"><label className="flex items-start gap-3 text-sm font-semibold"><input aria-describedby="consent-status" className="mt-0.5 size-4 accent-[#145c43]" defaultChecked={consented} name="productImprovementConsent" type="checkbox" /><span>Permitir uso futuro com consentimento</span></label><button className="button-secondary w-fit" type="submit">Salvar preferência</button></form><p className="mt-3 text-xs text-[#69736c]" id="consent-status">Status atual: {consented ? "consentimento registrado" : "desativado"}.</p></section>
      <section className="card p-5 sm:p-6"><div className="flex items-start gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-[#edf0f4] text-[#40536a]"><LockIcon size={18} /></span><div><h2 className="font-extrabold">Seus dados</h2><p className="mt-1 text-sm text-[#69736c]">Acesse e entenda o que está armazenado</p></div></div><div className="mt-5 divide-y divide-[#e8ebe6]"><Link className="group flex items-center justify-between gap-4 py-4 first:pt-0" href="/api/account/export"><span><span className="block font-bold">Exportar meus dados</span><span className="mt-1 block text-sm text-[#5b655e]">Baixe um arquivo JSON com seu perfil, currículos, vagas e análises.</span></span><DownloadIcon className="shrink-0 text-[#145c43] transition-transform group-hover:translate-y-0.5" size={19} /></Link><Link className="group flex items-center justify-between gap-4 py-4 last:pb-0" href="/privacidade"><span><span className="block font-bold">Ler política de privacidade</span><span className="mt-1 block text-sm text-[#5b655e]">Veja retenção, armazenamento e seus direitos no produto.</span></span><ArrowRightIcon className="shrink-0 text-[#145c43] transition-transform group-hover:translate-x-1" size={18} /></Link></div></section>
      <section className="rounded-[1.35rem] border border-[#e4beb9] bg-[#fff7f5] p-5 sm:p-6"><div className="flex items-start gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-[#ffe5e1] text-[#9a3e34]"><AlertIcon size={18} /></span><div className="min-w-0"><h2 className="font-extrabold text-[#7f3028]">Zona de exclusão</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#6c5652]">Excluir a conta remove permanentemente seus currículos, análises, preferências e arquivos privados. Essa ação não pode ser desfeita.</p><form action={deleteAccountAction} className="mt-5 max-w-md space-y-3"><label className="field-label text-[#7f3028]">Digite EXCLUIR para confirmar<input aria-describedby="delete-account-help" className="field-input mt-2 border-[#d9aaa4]" name="confirmation" pattern="EXCLUIR" required /></label><p className="text-xs leading-5 text-[#6c5652]" id="delete-account-help">A exclusão só será executada quando o texto for exatamente EXCLUIR.</p><button className="rounded-lg bg-[#9a3e34] px-4 py-2.5 text-sm font-bold text-white hover:bg-[#7f3028]" type="submit">Excluir minha conta</button></form></div></div></section>
    </div>
  </div>;
}